#!/bin/bash

# Inicializacia premennych
FILTER_AFTER=""
FILTER_BEFORE=""
FILTER_IP=""
FILTER_URI=""
COMMAND=""
FILES=""

# Spracovanie argumentov a nasledne posunutie
while [ $# -gt 0 ]; do
    case "$1" in
        -a) FILTER_AFTER="$2"; shift 2 ;;
        -b) FILTER_BEFORE="$2"; shift 2 ;;
        -ip) FILTER_IP="$2"; shift 2 ;;
        -uri) FILTER_URI="$2"; shift 2 ;;
        list-ip|list-hosts|list-uri|hist-ip|hist-load) COMMAND="$1"; shift ;;
        *) FILES="$FILES $1"; shift ;;
    esac
done

# Odstranenie medzier, pomplciek a dvojbodiek z datumu a casu pre nasledne porovnavanie
if [ -n "$FILTER_AFTER" ]; then
    FILTER_AFTER=$(echo "$FILTER_AFTER" | sed 's/[- :]//g') # sed 's/old/new/g' g pretoze nechcem nahradit iba 1. symbol v riadku
fi
if [ -n "$FILTER_BEFORE" ]; then
    FILTER_BEFORE=$(echo "$FILTER_BEFORE" | sed 's/[- :]//g') #
fi

read_inputs() {
    # Ak nemame zadane ziadne subory, citame zo standardneho vstupu pomocou "cat"
    if [ -z "$FILES" ]; then
        cat
    else
        for f in $FILES; do
            if [[ "$f" == *.gz ]]; then
                gzip -dc "$f" 2>/dev/null || zcat "$f"
            else
                cat "$f"
            fi
        done
    fi
}

read_inputs | awk -v after="$FILTER_AFTER" -v before="$FILTER_BEFORE" -v ip_fil="$FILTER_IP" -v uri_fil="$FILTER_URI" -v cmd="$COMMAND" '
BEGIN 
{
    # Mesiac na cislo
    m["Jan"]="01"; m["Feb"]="02"; m["Mar"]="03"; m["Apr"]="04"; m["May"]="05"; m["Jun"]="06"; m["Jul"]="07"; m["Aug"]="08"; m["Sep"]="09"; m["Oct"]="10"; m["Nov"]="11"; m["Dec"]="12";
}
    ip = $1
    uri = $7

[DD/Mon/YYYY:HH:MM:SS +TZ]
    # Ostranenie [ z datumu
    date_str = substr($4, 2)

    # Rozdelenie na casti podla / a :
    # d[1] = den, d[2] = mesiac, d[3] = rok, d[4] = hodina, d[5] = minuta, d[6] = sekunda
    split(date_str, d, /[\/:]/)

    date = log_date = d[3] m[d[2]] d[1] d[4] d[5] d[6]
    log_final_date = d[3] "-" m[d[2]] "-" d[1] " " d[4] ":00"
'